services:
  # mysql:  << REMOVE or comment out this whole service when using local DB >>

  php:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend:/var/www
    # depends_on: [mysql]   << REMOVE

  web:
    image: nginx:alpine
    volumes:
      - ./backend/public:/var/www/public
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./backend/storage:/var/www/storage
    depends_on: [php]
    ports: ["8080:80"]

  frontend-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile.build
    env_file: .env
    volumes:
      - ./frontend:/app
      - node_cache:/root/.npm
    command: ["sh","-c","npm install && npm run build"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    depends_on: [frontend-build]
    ports: ["5173:80"]

  mailhog:
    image: mailhog/mailhog
    ports: ["1025:1025","8025:8025"]

volumes:
  db_data:
  node_cache:
